### PR TITLE
Added missing disable/enable ckpt in WaitAny.

### PR DESCRIPTION
**Pull request by karya0**

### CODE REVIEW

**Review by xuyao0127 — APPROVED** [review]
LGTM

**Comment by karya0** [comment]
@JainTwinkle : I jumped the gun a few seconds too soon. Did you mean something like: https://github.com/mpickpt/mana/pull/276?

**Comment by JainTwinkle** [comment]
@karya0 yes! #276 looks correct to me. @xuyao0127 do you agree?

**Comment by xuyao0127** [comment]
I think @JainTwinkle is correct. We need to re-enable checkpoint after counters are updated. And @karya0 your new PR still has some problem. The second EANBLE_CKPT is after a return statement. So if it's returned, then it cannot re-enable checkpoint.

**Pull request merged**
