### PR TITLE
Feature/type info api expansion

### PR DESCRIPTION
**Pull request by chirag-singh1**
Same as earlier PR, but moved from memverge github to my personal github

### CODE REVIEW

**Review by gc00 — APPROVED** [review]
Since we're creating a new type here (e.g., `MPI_Type_create_hindexed'), don't we need to do log-and-replay on this?  Otherwise, on restart, the new MPI library won't know anything about the new type that was created prior to checkpoint.

If I'm right about this, then please add suitable comments with a `FIXME` explaining what is missing, and what still needs to be added.

But after you add the `FIXME`, it's fine to push this in.  I'm approving it in advance.

**Comment by chirag-singh1** [comment]
We actually don't have to because the logging is handled by MPI_hindexed (see the implementation of create_hindexed)

**Comment by gc00** [comment]
@chirag-singh1,
    Thanks for the comment.  Then this is ready to be pushed in (after rebasing).
Best,
- Gene

**Comment by JainTwinkle** [comment]
@chirag-singh1 I believe the second commit is stopping git to rebase-and-merge this branch. Could you improve the PR to get rid of the merge commit and have a single clean commit?

**Comment by chirag-singh1** [comment]
@JainTwinkle Should be fixed now

**Comment by JainTwinkle** [comment]
@chirag-singh1 Thanks! The PR is already approved. You can go ahead and merge it.

**Pull request merged**
