### PR TITLE
[MANA-45] Use DMTCP master branch.

### PR DESCRIPTION
**Pull request by karya0**
DMTCP is now included as a git submodule. Here are the steps to build the two:

````
~/test » git clone -b feature/dmtcp-master git@github.com:mpickpt/mana.git
Cloning into 'mana'...
remote: Enumerating objects: 34853, done.
remote: Counting objects: 100% (4302/4302), done.
remote: Compressing objects: 100% (1215/1215), done.
remote: Total 34853 (delta 3495), reused 3738 (delta 3080), pack-reused 30551
Receiving objects: 100% (34853/34853), 18.32 MiB | 11.91 MiB/s, done.
Resolving deltas: 100% (27468/27468), done.

~/test » cd mana

~/t/mana » git submodule init
Submodule 'dmtcp' (https://github.com/dmtcp/dmtcp) registered for path 'dmtcp'

~/t/mana » git submodule update
Cloning into '/home/kaarya/test/mana/dmtcp'...
Submodule path 'dmtcp': checked out '7b8dfab3e0debcffa21ee1fdf9a2e4822bfd66b1'

~/t/mana »./configure && make
```

It will make both DMTCP and MANA plugin.

### CODE REVIEW

**Comment by xuyao0127** [comment]
I found an issue in the bin directory. These mana scripts were in the same folder as dmtcp binaries. After updating the directory structure, paths for dmtcp binaries are pointing to the wrong locations. Also, scripts with and without ".sh" are the same. In the old mana, make is responsible to copy scripts with ".sh" to the bin directory and remove the extension name. Can we use something like soft link, or remove ".sh" versions since they are no longer needed?

**Comment by xuyao0127** [comment]
Just found another issue in the MANA scripts. mana_coordinator passes "--mpi" to the coordinator to enable MANA-related codes. But it seems we don't need it anymore.

**Comment by xuyao0127** [comment]
Several issues launching mpi programs:
1. mana_launch can't identify the coordinator hostname.
```
yaox@nid02353:~/mana_latest_dmtcp/mpi-proxy-split/test> srun -n 1 ~/mana_latest_dmtcp/bin/mana_launch -i 60 ./two-phase-commit-1.mana.exe
Coordinator not found. Please check port and host.
*** Checking for coordinator:
+ /global/homes/y/yaox/mana_latest_dmtcp/bin/dmtcp_command --status --coord-host nid00173 --coord-port 7779
Coordinator not found. Please check port and host.
+ set +x
  No coordinator detected.   Try:
    /global/homes/y/yaox/mana_latest_dmtcp/bin/mana_coordinator
  Or:
    /global/homes/y/yaox/mana_latest_dmtcp/bin/dmtcp_coordinator --mpi --exit-on-last -q --daemon
```

If launch with dmtcp_launch:

2. Programs linked with libmpidummy.so can't find the .so file.
```
./two-phase-commit-1.mana.exe: error while loading shared libraries: libmpidummy.so: cannot open shared object file: No such file or directory
```
3. Programs didn't linked with libmpidummy.so failed to launch with this error message:
```
execvp:: No such file or directory
```

**Comment by gc00** [comment]
@karya0,
    Jenkins is failing due to minor bugs in the `Makefile`.  Could you fix them and update?
In Jenkins, I'm seeing:
```
03:30:32 make: *** [Makefile:43: default] Error 2
03:30:32 + make clean
03:30:32 cd dmtcp && make clean
03:30:32 make[1]: Entering directory '/home/jenkins/workspace/mana_Pull_Request_Builder/dmtcp'
03:30:32 make[1]: *** No rule to make target 'clean'.  Stop.
03:30:32 make[1]: Leaving directory '/home/jenkins/workspace/mana_Pull_Request_Builder/dmtcp'
03:30:32 make: [Makefile:56: clean] Error 2 (ignored)
03:30:32 + make check
03:30:32 make: *** No rule to make target 'check'.  Stop.
03:30:32 + exit 1
```

and

```
03:30:32 + make clean
03:30:32 cd dmtcp && make clean
03:30:32 make[1]: Entering directory '/home/jenkins/workspace/mana_Pull_Request_Builder/dmtcp'
03:30:32 make[1]: *** No rule to make target 'clean'.  Stop.
```

and

```
03:30:32 cd dmtcp && make
03:30:32 make[1]: Entering directory '/home/jenkins/workspace/mana_Pull_Request_Builder/dmtcp'
03:30:32 make[1]: *** No targets specified and no makefile found.  Stop.
03:30:32 make[1]: Leaving directory '/home/jenkins/workspace/mana_Pull_Request_Builder/dmtcp'
03:30:32 make: *** [Makefile:51: dmtcp] Error 2
```

and

```
03:30:32 + cd /home/jenkins/workspace/mana_Pull_Request_Builder/ci/../contrib/mpi-proxy-split/unit-test
03:30:32 ci/unit-test.sh: line 12: cd: /home/jenkins/workspace/mana_Pull_Request_Builder/ci/../contrib/mpi-proxy-split/unit-test: No such file or directory
```

Hopefully, your new credentials now allow you to see the CI details yourself.

**Comment by gc00** [comment]
As discussed, we will add a tag, nersc-alpha-1 to the tip of feature/dmtcp-master on May 2.  Then, after a few days of checking that there are no missing commits on the master branch, we can rename 'master' to 'master-old', and then make 'master' a copy of the current feature/dmtcp-master.

**Pull request closed without merging**
