### PR TITLE
Update tests to run for longer time

### PR DESCRIPTION
**Pull request by chirag-singh-memverge**
I updated the tests to run for a predefined amount of wall time (including control over how long to sleep for)
I left out many of the send/recv tests because these methods are already covered thoroughly by the tests included

### CODE REVIEW

**Comment by chirag-singh-memverge** [comment]
@JainTwinkle Please review

**Comment by gc00** [comment]
@dahongli , This PR looks good, and I was about to approve it.  But you use the test s more often than I do.  Could you give this a quick look, and approve it if it seems okay?
We don't need a long and careful review.  If some test no longer runs well, it will be easy to individually fix that test later.

**Review by dahongli — CHANGES_REQUESTED** [review]
Thanks Chirag for the change. Overall, it looks good except Ibcast_test.

**Review by dahongli — APPROVED** [review]
Looks good. Thanks Chirag!

**Pull request closed without merging**
