### PR TITLE
Updated DMTCP to latest master.

### PR DESCRIPTION
**Pull request by karya0**
The latest DMTCP will now have DMTCP munmap the text/data/heap of mtcp_restart.  MANA will not need to worry about this in `mtcp_plugin_skip_memory_region_munmap`.  We can then update `mtcp_plugin_skip_memory_region_munmap` when this is pushed into main.

### CODE REVIEW

**Comment by JainTwinkle** [comment]
@karya0  I would like to hold this PR until #361 gets merged. It is because one of the commits changes the `rinfo` data structure.

**Comment by JainTwinkle** [comment]
@karya0 It's close to getting approved and merged (most likely, by the end of the day).

**Comment by gc00** [comment]
@karya0  ,  I also want to get #361 merged..  @JainTwinkle is dong a second review of PR #361 now.  I also want to push it in soon, to have a standard platform in the main branch.

**Comment by gc00** [comment]
And PR #361 is now merged.

**Review by JainTwinkle — APPROVED** [review]
LGTM.

**Pull request merged**
