### PR TITLE
[EQ-809][MANA-30]Create unit-test.sh

### PR DESCRIPTION
**Pull request by jackpao-memverge**
Add unit test. 
This will be used for jenkins pr test integration check.

### CODE REVIEW

**Comment by jackpao-memverge** [comment]
DrainTests is failed and known issue.

**Review by jungan — APPROVED** [review]

**Comment by jungan** [comment]
Thanks @jackpao-memverge, could you please help remove `drain-send-recv-test` from the Makefile and let CI can pass?
```
TESTS = record-replay-comm-test \
        record-replay-group-test \
        record-replay-types-test \
        record-replay-cart-test \
        drain-send-recv-test
```

**Comment by jackpao-memverge** [comment]
> Thanks @jackpao-memverge, could you please help remove `drain-send-recv-test` from the Makefile and let CI can pass?
> 
> ```
> TESTS = record-replay-comm-test \
>         record-replay-group-test \
>         record-replay-types-test \
>         record-replay-cart-test \
>         drain-send-recv-test
> ```
This pr is part of the effort for ci integration with jenkins test run. 
I don't have knowledge of the tests. 
Can the test owner made the change to the tests?

**Comment by jungan** [comment]
> > Thanks @jackpao-memverge, could you please help remove `drain-send-recv-test` from the Makefile and let CI can pass?
> > ```
> > TESTS = record-replay-comm-test \
> >         record-replay-group-test \
> >         record-replay-types-test \
> >         record-replay-cart-test \
> >         drain-send-recv-test
> > ```
> 
> This pr is part of the effort for ci integration with jenkins test run. I don't have knowledge of the tests. Can the test owner made the change to the tests?

OK, submitted PR #32 to remove it.
One question, is the Jenkins job will use the script in this code repo? I saw it's already running for other PRs as well but this script hasn't been merged in yet.
I suggest Jenkins job always get the latest script in the repo(or PR if has been updated), so later when we added more test cases and changed the script. It will be run by the Jenkins job automatically.

**Comment by jackpao-memverge** [comment]
> > > Thanks @jackpao-memverge, could you please help remove `drain-send-recv-test` from the Makefile and let CI can pass?
> > > ```
> > > TESTS = record-replay-comm-test \
> > >         record-replay-group-test \
> > >         record-replay-types-test \
> > >         record-replay-cart-test \
> > >         drain-send-recv-test
> > > ```
> > 
> > 
> > This pr is part of the effort for ci integration with jenkins test run. I don't have knowledge of the tests. Can the test owner made the change to the tests?
> 
> OK, submitted PR #32 to remove it. One question, is the Jenkins job will use the script in this code repo? I saw it's already running for other PRs as well but this script hasn't been merged in yet. I suggest Jenkins job always get the latest script in the repo(or PR if has been updated), so later when we added more test cases and changed the script. It will be run by the Jenkins job automatically.


I configured the jenkins and evertying before this pr, so it is already running. 
But once this script  is merged, it will use this script from the repo

**Comment by jungan** [comment]
test this please

**Pull request merged**
