### PR TITLE
[MANA-127] Get Fortran constant MPI_STATUSES_IGNORE

### PR DESCRIPTION
**Pull request by jungan**

### CODE REVIEW

**Review by dahongli — APPROVED** [review]
Good finding. Thanks Jun!

**Review by gc00 — APPROVED** [review]
@jungan,
    I found the following in the MPI standard.  Could you add all of the constants, and in a comment, refer to Section 2.5.4 (Named Constants)  of the 
MPI 3.1 standard, and quote the sentence "The constants that cannot be used in ...", somewhere in the code?

```
The constants that cannot be used in initialization expressions or assignments in Fortran are as follows:
MPI_BOTTOM
MPI_STATUS_IGNORE
MPI_STATUSES_IGNORE
MPI_ERRCODES_IGNORE
MPI_IN_PLACE
MPI_ARGV_NULL
MPI_ARGVS_NULL
MPI_UNWEIGHTED
MPI_WEIGHTS_EMPTY
```

After that, it looks good to me.  I'm approving this in advance.

**Comment by gc00** [comment]
I'll modify this to add the other FORTRAN constants before we push this in.

**Comment by jungan** [comment]
> I'll modify this to add the other FORTRAN constants before we push this in.

Hi Gene, I'm so sorry, my memverge email was suspended so I didn't get the notification.

If you haven't started yet, I can finish it and update the PR probably tomorrow. I will also see if I can find some proper test cases to verfiry those. Thanks!

**Comment by gc00** [comment]
@xuyao0127 , I've revised this PR to support more Fortran constants.  Could you give this a quick review?
(It's required to fix some bugs appearing elsewhere.)

It's similar to the support for MPI_IN_PLACE that we added a year ago.  But now, we have to support other Fortran constants, such as MPI_Statuses_ignore.

**Review by xuyao0127 — APPROVED** [review]
LGTM

**Pull request merged**
