### PR TITLE
Update unit-test.sh

### PR DESCRIPTION
**Pull request by jackpao-memverge**
GCC 8 or higher for build env

### CODE REVIEW

**Comment by jungan** [comment]
Hi @jackpao-memverge , I found the CI actually ignores the compile error, could you please help fix it?

**Review by gc00 — APPROVED** [review]
LGTM.  (Thanks, @jackpao-memverge.)

**Review by dahongli — APPROVED** [review]

**Comment by gc00** [comment]
@jackpao-memverge, I see that the build is failing with this error message:
```
14:11:36 /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -llzma
14:11:36 /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lz
14:11:36 /opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lxml2
```
It's actually looking for the static libraries:  liblzma.a, libz.a, libxml2.a

The reason for this is that it needs the rpm binary packages for `libxml2-static`, `libz-static` and `liblzma-static`.  At least, I think those are the correct package names for those librries on Red Hat.  IF I'm wrong on any of them, a little googling will find you the correct pacakge for the static library.

**Comment by jackpao-memverge** [comment]
test this please

**Comment by tomw-mv** [comment]
test this please

**Pull request merged**
